---
title: "SCF Finances"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidymodels)
```

```{r}
df <- read_csv("SCFP2019.csv")
```

to make this useable I need to translate parts of this SAS code into R
https://www.federalreserve.gov/econres/files/bulletin.macro.txt

there is a flow chart that gives variable names here
https://www.federalreserve.gov/econres/files/Networth%20Flowchart.pdf

there appears to be an online codebook for the final dataset that is extremely slow:
https://sda.berkeley.edu/sdaweb/docs/scfcomb2019/DOC/hcbk.htm;jsessionid=40FDDFAC459F31A7672973E95905B08A

```{r}
# while it's not exactly right to set log(0) to be 0, in practice this doesn't impact results. And leaving it at -Inf is not an option
log0 <- function(x) {
  x <- log(x)
  x <- replace(x, !is.finite(x), 0)
}

#recoding some key variables
df_glp <- df %>%
  mutate(
    age = AGE,
    age_sq = age^2,
    kids = KIDS,
    labor_force = LF,
    net_worth = NETWORTH,
    vehicle = OWN,
    income = INCOME,
    inc_sq = income^2,
    inc_cub = income^3,
    log_inc = log0(income),
    monthly_rent = RENT,
    wgt = WGT,
    race = case_when(
      RACE == 1 ~ "White",
      RACE == 2 ~ "Black",
      RACE == 3 ~ "Hispanic",
      RACE == 5 ~ "Other",
    ),
    home_owner = case_when(HOUSECL == 1 ~ 1,
                           HOUSECL == 2 ~ 0),
    married = case_when(MARRIED == 1 ~ 1,
                        MARRIED == 2 ~ 0),
    educ = case_when(
      EDCL == 1 ~ "no hs degree",
      EDCL == 2 ~ "hs degree",
      EDCL == 3 ~ "some college",
      EDCL == 4 ~ "college degree"
    )
  ) %>%
  select(log_inc, income, inc_sq, inc_cub, age, age_sq, kids, labor_force, race, vehicle, monthly_rent, home_owner, married, educ, net_worth, wgt)
```


```{r}
ggplot(df_glp, aes(x = income, y = net_worth)) +
  geom_point()
```


```{r}
lm0 <- lm(net_worth ~ income, data = df_glp)
summary(lm0)
```


```{r}
lm1 <- lm(net_worth ~ income + age + age_sq + kids + labor_force + vehicle + monthly_rent + home_owner + married + educ + race, data = df_glp)
summary(lm1)
```
Let's try log values for income
This makes it much worse
```{r}
lm2 <- lm(net_worth ~ log_inc + age + age_sq + kids + labor_force + vehicle + monthly_rent + home_owner + married + educ + race, data = df_glp)
summary(lm2)
```
## Tidymodels time

Testing and training sets
```{r}
set.seed(42)
scf_split <- initial_split(df_glp, prop = 0.80)

scf_train <- training(scf_split)
scf_test <- testing(scf_split)
```


```{r}
simple_scf <- 
  recipe(net_worth ~ income + age + age_sq + kids + labor_force + vehicle + monthly_rent + home_owner + married + educ + race,
         data = df_glp) %>%
  step_dummy(educ, race)

prepped_scf <- prep(simple_scf, training = scf_train)

baked_scf <- bake(prepped_scf, new_data = scf_train)
```

#recreate our initial model
```{r}
lm_fit <- lm(net_worth ~ ., data = baked_scf)
summary(lm_fit)
```
```{r}
lm_model <- linear_reg() %>%
  set_engine("lm")
```


```{r}
lm_wflow <-
  workflow() %>%
  add_model(lm_model) %>%
  add_recipe(simple_scf)

lm_fit <- fit(lm_wflow, scf_train)
```


```{r}
scf_test_res <- predict(lm_fit, new_data = scf_test %>% select(-net_worth))
scf_test_res <- bind_cols(scf_test_res, scf_test %>% select(net_worth))
head(scf_test_res)
```

```{r}
ggplot(scf_test_res, aes(x = net_worth, y = .pred)) +
  geom_abline(lty = 2) + #dashed line
  geom_point(alpha = 0.5) 
```


```{r}
rmse(scf_test_res, truth = net_worth, estimate = .pred)
```

Trying with xgboost

```{r}
xgb_spec <- boost_tree(
  trees = 1000) %>%
  set_engine("xgboost") %>% 
  set_mode("regression")

xgb_spec

xgb_grid <- grid_latin_hypercube(
  tree_depth(),
  min_n(),
  loss_reduction(),
  sample_size = sample_prop(),
  finalize(mtry(), scf_train),
  learn_rate(),
  size = 30
)

xgb_grid

xgb_wf <- workflow() %>%
  add_formula(net_worth ~ .) %>%
  add_model(xgb_spec)

xgb_wf
```

```{r}
xgb_fit <- fit(xgb_wf, scf_train)
```

```{r}
scf_test_res <- predict(xgb_fit, new_data = scf_test %>% select(-net_worth))
scf_test_res <- bind_cols(scf_test_res, scf_test %>% select(net_worth))
head(scf_test_res)
```

```{r}
rmse(scf_test_res, truth = net_worth, estimate = .pred)
```

```{r}
scf_test_plt <- scf_test_res %>%
  mutate(nw_mil = net_worth/1000000,
         pred_mil = .pred/1000000)

ggplot(scf_test_plt, aes(x = nw_mil, y = pred_mil)) +
  geom_abline(lty = 2) + #dashed line
  geom_point(alpha = 0.5) 
```

